# Generated by Django 5.2.4 on 2025-07-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Land",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manual_id", models.CharField(max_length=5)),
                ("block", models.CharField(max_length=5)),
                ("length", models.DecimalField(decimal_places=2, max_digits=10)),
                ("width", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("residential", "Residencial"),
                            ("commercial", "Comercial"),
                            ("industrial", "Industrial"),
                            ("agricultural", "Agrícola"),
                            ("recreational", "Recreativo"),
                            ("other", "Otro"),
                        ],
                        default="residential",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Disponible"),
                            ("sold", "Vendido"),
                            ("reserved", "Reservado"),
                            ("under_contract", "Bajo contrato"),
                            ("not_available", "No disponible"),
                        ],
                        default="available",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Terreno",
                "verbose_name_plural": "Terrenos",
                "ordering": ["manual_id"],
            },
        ),
    ]
