# Generated by Django 4.2.23 on 2025-06-23 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sellers", "0001_initial"),
        ("lands", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="land",
            name="size",
        ),
        migrations.AlterField(
            model_name="land",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sellers.seller",
            ),
        ),
    ]
