# Generated by Django 5.2.4 on 2025-12-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lands", "0002_land_project_land_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="land",
            name="currency",
            field=models.CharField(default="USD", max_length=5),
        ),
    ]
