# Generated by Django 4.2.23 on 2025-06-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lands", "0002_remove_land_size_alter_land_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="land",
            name="length",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="land",
            name="width",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
