# Generated by Django 4.2.23 on 2025-06-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lands", "0003_land_length_land_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="land",
            name="length",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="land",
            name="width",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
