# Generated by Django 4.2.23 on 2025-07-09 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payment_receivers", "0001_initial"),
        ("expense_types", "0001_initial"),
        ("projects", "0001_initial"),
        ("payers", "0001_initial"),
        ("expense_type_details", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "currency",
                    models.CharField(
                        choices=[("ars", "Pesos"), ("usd", "Dolares")], max_length=3
                    ),
                ),
                ("exchange_rate", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("cash", "Efectivo"),
                            ("transfer", "Transferencia"),
                            ("cheque", "Cheque"),
                            ("debit_card", "tarjeta de Débito"),
                            ("credit_card", "Tarjeta de Cédito"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("accountant", models.BooleanField(default=False)),
                (
                    "accountant_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "accountant_currency",
                    models.CharField(
                        blank=True,
                        choices=[("ars", "Pesos"), ("usd", "Dolares")],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expense_type_details.expensetypedetail",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payers.payer",
                    ),
                ),
                (
                    "payment_receiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payment_receivers.paymentreceiver",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expense_types.expensetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inversión",
                "verbose_name_plural": "Inversiones",
                "ordering": ["date"],
            },
        ),
    ]
