# Generated by Django 5.2.4 on 2025-07-11 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense_type_details", "0001_initial"),
        ("expense_types", "0001_initial"),
        ("investments", "0001_initial"),
        ("payers", "0001_initial"),
        ("payment_receivers", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="expense_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="expense_types.expensetype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="investment",
            name="expense_type_detail",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="expense_type_details.expensetypedetail",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="investment",
            name="payer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payers.payer",
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="payment_receiver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payment_receivers.paymentreceiver",
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
            preserve_default=False,
        ),
    ]
