# Generated by Django 5.2.4 on 2025-07-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0002_investment_expense_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
    ]
