# Generated by Django 5.2.4 on 2025-07-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense_type_details", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensetypedetail",
            name="key",
            field=models.CharField(max_length=100, unique=True, null=True),
            preserve_default=False,
        ),
    ]
