# Generated by Django 5.2.4 on 2025-07-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense_type_details", "0002_expensetypedetail_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensetypedetail",
            name="key",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
