# Generated by Django 5.2.4 on 2025-12-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expense_type_details", "0003_alter_expensetypedetail_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expensetypedetail",
            options={
                "ordering": ["description"],
                "verbose_name": "Detalle de Inversión",
                "verbose_name_plural": "Detalles de Inversióon",
            },
        ),
    ]
