"""
Django settings for terrenos project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url
import django_heroku
from django.core.exceptions import ImproperlyConfigured

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_TERRENOS_DEBUG", "").strip().lower() in ("1", "true", "yes", "on")

ALLOWED_HOSTS = ['terrenos-429b9d4cf9d7.herokuapp.com', 'localhost', '127.0.0.1']

CSRF_TRUSTED_ORIGINS = [
    'https://terrenos-429b9d4cf9d7.herokuapp.com',
    'http://localhost:8000'
]

# Application definition

DEFAULT_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "whitenoise.runserver_nostatic",
    "django_bootstrap5"
]

CUSTOM_APPS = [
    "expense_type_details",
    "expense_types",
    "expenses",
    "investments",
    "lands",
    "payers",
    "payment_receivers",
    "people",
    "people_to_lands",
    "projects",
    "sales",
    "sales_summary",
    "sellers",
    "users"
]

INSTALLED_APPS = DEFAULT_APPS + CUSTOM_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "terrenos.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "terrenos.wsgi.app"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

## La conexion sale siempre del entorno, nunca hardcodeada:
##   - en Heroku, de la config var DATABASE_URL (hoy apunta a Neon)
##   - en desarrollo, de DATABASE_URL en el .env local
## dj_database_url parsea la URL entera (usuario, password, host, sslmode, ...),
## asi que no hace falta desarmarla a mano con urlparse. Ojo: si la variable no
## existe, urlparse(None) devuelve bytes y el error resultante no dice nada util.
DATABASE_URL = os.environ.get("DATABASE_URL") or os.environ.get("NEON_TERRENOS_DATABASE_URL")

if not DATABASE_URL:
    raise ImproperlyConfigured(
        "Falta DATABASE_URL. En local definila en .env; en Heroku es una config var "
        "(heroku config:set DATABASE_URL=...)."
    )

## Neon exige SSL; el Postgres local normalmente no lo tiene configurado.
_IS_LOCAL_DB = "localhost" in DATABASE_URL or "127.0.0.1" in DATABASE_URL

DATABASES = {
    "default": dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        ssl_require=not _IS_LOCAL_DB,
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-ar"

TIME_ZONE = "America/Argentina/Buenos_Aires"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = BASE_DIR / "staticfiles"

STATIC_URL = "/static/"

# Project-level static assets (currently only the public landing page).
# Without this, AppDirectoriesFinder alone would never see terrenos/static/.
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_REDIRECT_URL = "/"

## Solo en Heroku. django_heroku reescribe DATABASES (forzando sslmode=require),
## ALLOWED_HOSTS, STATIC_* y LOGGING; corriendolo en desarrollo le imponia SSL al
## Postgres local apenas DATABASE_URL aparecio en el .env. DYNO existe en los dynos
## (web, run y release) pero no durante el build, que solo necesita STATIC_*.
if os.environ.get("DYNO"):
    django_heroku.settings(locals())