# Generated by Django 5.2.3 on 2025-06-22 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sales", "0001_initial"),
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sale", "Venta"),
                            ("payment", "Pago"),
                            ("boletus", "Boletus"),
                            ("deed", "Escritura"),
                        ],
                        default="sale",
                        max_length=50,
                    ),
                ),
                ("accountant", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("exchange_rate", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.sale"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sellers.seller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resumen de Ventas",
                "verbose_name_plural": "Resumenes de Ventas",
                "ordering": ["date"],
            },
        ),
    ]
