# Generated by Django 5.2.4 on 2025-07-11 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("initial_payment", "Pago Inicial"),
                            ("monthly_payment", "Cuota"),
                            ("remaining_payment", "Pago de Saldo Restante"),
                        ],
                        default="sale",
                        max_length=50,
                    ),
                ),
                (
                    "payment_option",
                    models.CharField(
                        choices=[
                            ("pesos", "Pesos"),
                            ("usd", "Dolares"),
                            ("cheque", "Cheque"),
                            ("tranfer", "Tranferencia"),
                        ],
                        max_length=50,
                    ),
                ),
                ("accountant", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("exchange_rate", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sellers.seller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resumen de Ventas",
                "verbose_name_plural": "Resumenes de Ventas",
                "ordering": ["date"],
            },
        ),
    ]
