# Generated by Django 5.2.4 on 2025-07-11 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_sale_land"),
        ("sales_summary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesummary",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salesummary",
            name="sale",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="sales.sale"
            ),
            preserve_default=False,
        ),
    ]
