# Generated by Django 4.2.23 on 2025-06-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_summary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesummary",
            name="payment_option",
            field=models.CharField(
                choices=[
                    ("pesos", "Pesos"),
                    ("usd", "Dolares"),
                    ("cheque", "Cheque"),
                    ("tranfer", "Tranferencia"),
                ],
                default="pesos",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="salesummary",
            name="type",
            field=models.CharField(
                choices=[
                    ("initial_payment", "Pago Inicial"),
                    ("monthly_payment", "Cuota"),
                    ("remaining_payment", "Pago de Saldo Restante"),
                ],
                default="sale",
                max_length=50,
            ),
        ),
    ]
