# Generated by Django 5.2.4 on 2025-12-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expense_types", "0003_alter_expensetype_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expensetype",
            options={
                "ordering": ["description"],
                "verbose_name": "Concepto de Inversión",
                "verbose_name_plural": "Conceptos de Inversión",
            },
        ),
    ]
