# Generated by Django 5.2.4 on 2025-07-11 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lands", "0002_land_project_land_seller"),
        ("people", "0001_initial"),
        ("people_to_lands", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="peopletolands",
            options={
                "ordering": ["person", "land"],
                "verbose_name": "Persona a Terreno",
                "verbose_name_plural": "Personas a Terrenos",
            },
        ),
        migrations.AddField(
            model_name="peopletolands",
            name="land",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="lands.land"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="peopletolands",
            name="person",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="people.people",
            ),
            preserve_default=False,
        ),
    ]
