# Generated by Django 5.2.4 on 2025-07-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "currency",
                    models.CharField(
                        choices=[("ars", "Pesos"), ("usd", "Dolares")], max_length=3
                    ),
                ),
                ("exchange_rate", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("cash", "Efectivo"),
                            ("transfer", "Transferencia"),
                            ("cheque", "Cheque"),
                            ("debit_card", "tarjeta de Débito"),
                            ("credit_card", "Tarjeta de Cédito"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("receipt", models.FileField(upload_to="uploads/")),
                ("accountant", models.BooleanField(default=False)),
                (
                    "accountant_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "accountant_currency",
                    models.CharField(
                        blank=True,
                        choices=[("ars", "Pesos"), ("usd", "Dolares")],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Gasto",
                "verbose_name_plural": "Gastos",
                "ordering": ["date"],
            },
        ),
    ]
