# Generated by Django 5.2.3 on 2025-06-22 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("detail", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("maintenance", "Mantenimiento"),
                            ("utilities", "Servicios"),
                            ("taxes", "Impuestos"),
                            ("other", "Otro"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("accountant", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("exchange_rate", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sellers.seller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto",
                "verbose_name_plural": "Gastos",
                "ordering": ["date"],
            },
        ),
    ]
