# Generated by Django 4.2.23 on 2025-06-26 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payment_receivers", "0001_initial"),
        ("payers", "0001_initial"),
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="seller",
        ),
        migrations.AddField(
            model_name="expense",
            name="currency",
            field=models.CharField(
                choices=[("ars", "Pesos"), ("usd", "Dolares")],
                default="ars",
                max_length=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expense",
            name="payer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payers.payer",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="payment_receiver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payment_receivers.paymentreceiver",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("cash", "Efectivo"),
                    ("transfer", "Transferencia"),
                    ("cheque", "Cheque"),
                    ("debit_card", "tarjeta de Débito"),
                    ("credit_card", "Tarjeta de Cédito"),
                    ("other", "Otro"),
                ],
                default="cash",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="expense",
            name="detail",
            field=models.CharField(
                choices=[
                    ("boletus", "Boleto"),
                    ("deed", "Escritura"),
                    ("absa_feasibility", "Factibilidad ABSA"),
                    ("municipal_visa", "Visado Municipal"),
                    ("honorarium", "Honorarios"),
                    ("sign", "Cartel"),
                    ("wiring", "Alambrado"),
                    ("labour", "Mano de Obra"),
                    ("materials", "Materiales"),
                    ("taxes", "Impuestos"),
                    ("freight", "Flete"),
                    ("cleaning", "Limpieza"),
                    ("maintainance", "Mantenimiento"),
                    ("street_opening", "Apertura de Calles"),
                    ("street_canal", "Canal"),
                    ("street_filling", "Relleno de Calles"),
                    ("other", "Otro"),
                ],
                default="sign",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="expense",
            name="type",
            field=models.CharField(
                choices=[
                    ("plans", "Planos"),
                    ("measurement", "Mensura"),
                    ("streets", "Calles"),
                    ("property", "Inmueble"),
                    ("gas_project", "Obra de Gas"),
                    ("light_project", "Obra de Luz"),
                    ("other", "Otro"),
                ],
                max_length=50,
            ),
        ),
    ]
