# Generated by Django 4.2.23 on 2025-07-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="receipt",
            field=models.FileField(default="initial", upload_to="uploads/"),
            preserve_default=False,
        ),
    ]
