# Generated by Django 5.2.4 on 2025-07-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_expense_expense_type_expense_expense_type_detail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
    ]
