# Generated by Django 4.2.23 on 2025-06-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "expenses",
            "0002_remove_expense_seller_expense_currency_expense_payer_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="accountant_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="accountant_currency",
            field=models.CharField(
                blank=True,
                choices=[("ars", "Pesos"), ("usd", "Dolares")],
                max_length=3,
                null=True,
            ),
        ),
    ]
