# Generated by Django 5.2.4 on 2025-12-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="people",
            name="type",
            field=models.CharField(
                choices=[
                    ("interested", "Interesado"),
                    ("buyer", "Comprador"),
                    ("other", "Otro"),
                ],
                default="interested",
                max_length=50,
            ),
        ),
    ]
