# Generated by Django 4.2.23 on 2025-07-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="people",
            name="type",
            field=models.CharField(
                choices=[
                    ("buyer", "Comprador"),
                    ("interested", "Interesado"),
                    ("other", "Otro"),
                ],
                default="individual",
                max_length=50,
            ),
        ),
    ]
