# Generated by Django 5.2.3 on 2025-06-22 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lands", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sale_date", models.DateField()),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("n_payments", models.IntegerField(default=1)),
                ("boletus_date", models.DateField(blank=True, null=True)),
                ("deed_date", models.DateField(blank=True, null=True)),
                ("deed_number", models.CharField(blank=True, max_length=20, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "land",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lands.land"
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
                "ordering": ["sale_date"],
            },
        ),
    ]
