# Generated by Django 4.2.23 on 2025-06-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("completed", "Completada"),
                    ("cancelled", "Cancelada"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
