# Generated by Django 5.2.4 on 2025-07-11 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lands", "0002_land_project_land_seller"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="land",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="lands.land"
            ),
            preserve_default=False,
        ),
    ]
